[package]
name = "docker-mgmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
async-trait = "0.1.74"
docker-api = "0.14"
serde = "1.0.192"
serde_derive = "1.0.192"

